name: 'CI Test Linux'

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: 'x64'
          cache: 'gradle'

      - run: ./gradlew test --warning-mode fail
